resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: Deployment-nginx
  type: git
  source:
    uri: https://github.com/sahumanoj3119/automatenginx.git
- name: boshrelease-nginx
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/nginx-release
- name: boshrelease-haproxy
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/haproxy-boshrelease
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version_family: latest

- name: deploy-nginx
  type: bosh-deployment
  source:
    deployment: nginx
    target: 10.100.155.80
    client: admin
    client_secret: xohnbqmirqijx8vrstz6
    ca_cert: |
     -----BEGIN CERTIFICATE-----
     MIIEVDCCArygAwIBAgIRAJ4ceeZMmfkT7pKBHiA5W3EwDQYJKoZIhvcNAQELBQAw
     MzEMMAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MQswCQYDVQQD
     EwJjYTAeFw0xOTEyMTMxMDU4MDJaFw0yMDEyMTIxMDU4MDJaMDMxDDAKBgNVBAYT
     A1VTQTEWMBQGA1UEChMNQ2xvdWQgRm91bmRyeTELMAkGA1UEAxMCY2EwggGiMA0G
     CSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC9WfLY6DOit2uKNPdBl9tOMFrwoIpC
     j2hFje9UBaEM2EqWwxJKql59cm6UWEs0bpO+9/TlbH5SsKf/442HbJtHDEv1LIsx
     HAD37PM11eIhDpgkmjja0LV6xub0b49Yof34KgDdGS//RqjaYRrrgIWjrzp/tHdr
     6tNrMf5x/aTovJxVCyPw7AFO5HNUIV7omMPXNzTCr/Rj3D9s7lp0zki1j6ba6wlv
     Xv8+y21HMTARtRNnPQOk2UN+1cDeeU2DzW0WLhInsoKz/k64cU6IJcqpSm6Di9Bp
     M+y1OaJeVw4gI/9H8sWImomyO0wHS1HOJQp0APwSVcnuZVQg7a1zjWpn0DdrQUyY
     uvhT1uH5hQGVeByDFyiVar9uh0H/kWtMPHKcnittTshiOTI5S1ohAO8iFN/H/BNQ
     rTWDfsEMbbQq8u/VkbcTLZ0DWTktAp84WytOETjMdYOiu+gJm5ds0JPUx/QarJbH
     PB1e3JD1Fbud0x8hcheGVWGdCgVNVDxd640CAwEAAaNjMGEwDgYDVR0PAQH/BAQD
     AgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBsFuoHS6MhVl9Xm16+FQ9Ut
     g0uUMB8GA1UdIwQYMBaAFBsFuoHS6MhVl9Xm16+FQ9Utg0uUMA0GCSqGSIb3DQEB
     CwUAA4IBgQA22Lntf/NqqW4Ln+4QIbyNIUedVUPrgpSjUzeQRd2VGn6vVF7EGD+m
     AROQmeD6lt0GhWL33YktkTPMHADsFRc/J2C0RIkmaKhxU51a4yFq5/XuE1g72Gjx
     86mYq8Ps9mHsSxKvZuzPdisfDeXNUM07DTaXPgkJ9T27O2XsnNR9aF1Z8nmh9ri5
     OQDdgP/Xu8FvSQebvnwEPRO5V/J9Hm7oJ6QcaQhOE2MY40z2t4em9kQzBfjurP/+
     mImeH6zix1zUgqj1U7vdvIJe25vOKoppCuHb/wGBTlfOkyu/smS9yrh/SjKPUID6
     jYjdSryHJzGOElcwKT9DntPIXudzKISeo0/4zGGlxj57cOlf2n7KAmMKVIHD3Jsy
     qwekHl+GkG9Gx2KPyVwDrzkH9U9Wb2/glRQRLSyR/3v1EE/nQFlUDhu0Zgwmu6vP
     DvMFi56VQ3+08a1t9aSWFiZAmXx9l9qulSdHkzNj73rLmp+QheXhWgjr0W8lNm+z
     n8S5b8q9HFU=
     -----END CERTIFICATE-----

jobs:
- name: deploy-nginx
  plan:
  - aggregate:
    - get: boshrelease-haproxy
      trigger: true
    - get: Deployment-nginx
      trigger: true
    - get: stemcell
      trigger: true
    - get: boshrelease-nginx
      trigger: true
  - put: deploy-nginx
    params:
      manifest: Deployment-nginx/nginx.yml
      stemcells:
      - stemcell/stemcell.tgz
      releases:
      - boshrelease-nginx/release.tgz
      - boshrelease-haproxy/release.tgz
